name: CI/CD Pipeline
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        run: |
          cd /pycaret-demo
          docker-compose down
          docker-compose pull
          docker-compose up -d