name: CI/CD Pipeline
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Log into registry
        uses: actions/checkout@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker build
        uses: docker/setup-buildx-action@v1
        
      - name: Create image
        run: ls -lah && cd pycaret-demo && docker build .