name: docker-auto-test

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Log into registry
        uses: actions/checkout@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor}}
         password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pycaret-demo .
          push: true
          tags: ghcr.io/th3-gr3ym4n/knime-for-docker/knimewithpython:latest

        # run: docker build . --file Dockerfile
          
