name: Build Docker Image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'ghcr.io/th3-gr3ym4n/knime-for-docker/knimewithpython:latest'

# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}