name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup docker build
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          # Build the Docker image
          docker build pycaret-demo \
            --tag ghcr.io/th3-gr3ym4n/knime-for-docker/knimewithpython:latest \
            --file pycaret-demo/Dockerfile.pycaret

          # Log into the Docker registry (assuming you have set your credentials already)
          docker login ghcr.io -u ${{ github.repository_owner }} --password ${{ secrets.DOCKER_TOKEN }}

          # Push the Docker image to the registry
          docker push ghcr.io/th3-gr3ym4n/knime-for-docker/knimewithpython:latest


        